### PR TITLE
Upgrade to Spring Boot 3

### PR DESCRIPTION
**Pull request by rvullriede**
- Upgrade to Spring Boot 3 and Spring Framework 6
- javax ->jakarta migration
- In addition, upgrade dependencies and adjust demos to latest spring configuration properties.
- add missing maven wrapper to webflux demo

Both demo apps are working properly.

### CODE REVIEW

**Review by michael-simons — APPROVED** [review]

**Comment by michael-simons** [comment]
@torstenmandry Hey Torsten, I gave this a quick sanity check, looks good from my perspective. But I am personally not really involved in this project. I'm happy to merge it if someone else who is using the starter might have a look, too. In case you aren't, you maybe know someone who is. Thanks.

**Comment by michael-simons** [comment]
Thanks @rvullriede for your time and effort, appreciated!

I would probably remove the wrapper binary jar (the wrapper can do without). And if you might rebase on master and bump the JDK in the `.github/workflows/build.yml` to 17, we might even see a green test here.

**Comment by rvullriede** [comment]
Hi @michael-simons , thanks for your review and the comments. I've updated the PR with the following changes:

- removed unneeded wrapper binaries
- updated github actions to latest versions (v3) and to Java 17
- updated npm dependencies used in the demos to their latest versions.

**Comment by michael-simons** [comment]
Excellent catch with the outdated actions 😅 me copy and pasting things in the night.

**Comment by michael-simons** [comment]
Thanks @rvullriede I merged this.

**Comment by rvullriede** [comment]
thx @michael-simons :-) Is there a chance to also publish a release (incl. maven central) so it's easy for people to pick it up?
I'm happy to provide a README update so it's clear which version works for which Spring Boot version.

**Comment by michael-simons** [comment]
@rvullriede https://repo.maven.apache.org/maven2/org/faucet-pipeline/faucet-pipeline-spring-boot-starter/2.0.0/ 

;)

And yes, I would love to have an update to the readme along the lines "1.3.0 is for Spring Boot 2.x, 2.x for Spring Boot 3.x"

**Pull request merged**
